#!/bin/bash
#
# Epoxy test suite
#
# Copyright (c) 2013 Red Hat, Inc. All rights reserved.
#
# This copyrighted material is made available to anyone wishing
# to use, modify, copy, or redistribute it subject to the terms
# and conditions of the GNU General Public License version 2.

. ep.sh
ep_suite_init "$@"

ep_suite glob glob
ep_suite_begin log; (
    ep_suite_init
    ep_suite mix log_mix
    ep_suite filter log_filter
    ep_suite cook log_cook
); ep_suite_end
ep_suite status status
