#!/bin/bash
#
# Bash test test suite
#
# Copyright (c) 2013 Red Hat, Inc. All rights reserved.
#
# This copyrighted material is made available to anyone wishing
# to use, modify, copy, or redistribute it subject to the terms
# and conditions of the GNU General Public License version 2.

. bt.sh
bt_suite_init "$@"

bt_suite glob glob
bt_suite glob_escape glob_escape
bt_suite_begin log; (
    bt_suite_init
    bt_suite mix log_mix
    bt_suite filter log_filter
    bt_suite cook log_cook
); bt_suite_end
bt_suite status status
