#!/bin/bash
#
# Suite status handling test suite
#
# Copyright (c) 2012-2013 Red Hat, Inc. All rights reserved.
#
# This copyrighted material is made available to anyone wishing
# to use, modify, copy, or redistribute it subject to the terms
# and conditions of the GNU General Public License version 2.

. ep.sh
ep_suite_init "$@"

# Test an exit status assertion
# Args: status_suffix name
# Input: test suite script without ep_suite_init.sh sourcing
function t()
{
    declare -r name="$1"
    declare -r status_suffix="$2"
    declare -r status_name="EP_STATUS_`echo $status_suffix | tr a-z A-Z`"

    ep_test_begin -e "${!status_name}" "$name"; (
        ep_test_init
        {
            echo '. ep.sh'
            echo 'ep_suite_init "$@"'
            cat
        } | EP_PROTOCOL=suite bash -s -- --raw --unfiltered || exit $?
    ); ep_test_end
}

t empty PASSED <<<"
"

ep_suite_begin setup; (
    ep_suite_init

    ep_suite_begin one; (
        ep_suite_init
        t ok      PASSED    <<<"true"
        t fail    ERRORED   <<<"false"
    ); ep_suite_end

    ep_suite_begin two; (
        ep_suite_init
        t fail_fail       ERRORED   <<<"false;  false"
        t fail_ok         ERRORED   <<<"false;  true"
        t ok_fail         ERRORED   <<<"true;   false"
        t ok_ok           PASSED    <<<"true;   true"
    ); ep_suite_end
); ep_suite_end

ep_suite_begin teardown; (
    ep_suite_init

    ep_suite_begin one; (
        ep_suite_init
        t ok      PASSED    <<<"ep_teardown_push true"
        t fail    PANICKED  <<<"ep_teardown_push false"
    ); ep_suite_end

    ep_suite_begin two; (
        ep_suite_init
        t fail_fail       PANICKED  <<<"
            ep_teardown_push false; ep_teardown_push false"
        t fail_ok         PANICKED  <<<"
            ep_teardown_push false; ep_teardown_push true"
        t ok_fail         PANICKED  <<<"
            ep_teardown_push true;  ep_teardown_push false"
        t ok_ok           PASSED    <<<"
            ep_teardown_push true;  ep_teardown_push true"
    ); ep_suite_end
); ep_suite_end

ep_suite_begin setup_teardown; (
    ep_suite_init
    t ok_ok       PASSED    <<<"true;   ep_teardown_push true"
    t fail_ok     ERRORED   <<<"false;  ep_teardown_push true"
    t ok_fail     PANICKED  <<<"true;   ep_teardown_push false"
    t fail_fail   ERRORED   <<<"false;  ep_teardown_push false"
); ep_suite_end

ep_suite_begin teardown_setup; (
    ep_suite_init
    t ok_ok       PASSED    <<<"ep_teardown_push true;  true"
    t fail_ok     PANICKED  <<<"ep_teardown_push false; true"
    t ok_fail     ERRORED   <<<"ep_teardown_push true;  false"
    t fail_fail   PANICKED  <<<"ep_teardown_push false; false"
); ep_suite_end

ep_suite_begin test; (
    ep_suite_init

    t no_args   ABORTED <<<"ep_test" 2>/dev/null

    ep_suite_begin options; (
        ep_suite_init
        t none                  PASSED  <<<"ep_test               1"
        t w                     WAIVED  <<<"ep_test -w            1"
        t waived                WAIVED  <<<"ep_test --waived      1"
        t s                     SKIPPED <<<"ep_test -d            1"
        t skipped               SKIPPED <<<"ep_test --disabled    1"
        t e0                    PASSED  <<<"ep_test -e0           1   true"
        t e1                    PASSED  <<<"ep_test -e1           1   false"
        t expected_eq_0         PASSED  <<<"ep_test --expected=0  1   true"
        t expected_eq_1         PASSED  <<<"ep_test --expected=1  1   false"
    ); ep_suite_end

    ep_suite_begin one; (
        ep_suite_init
        t empty                 PASSED  <<<"ep_test       1"
        t empty_waived          WAIVED  <<<"ep_test -w    1"
        t empty_skipped         SKIPPED <<<"ep_test -d    1"
        t empty_waived_skipped  SKIPPED <<<"ep_test -w -d 1"
        t ok                    PASSED  <<<"ep_test       1 true"
        t ok_waived             WAIVED  <<<"ep_test -w    1 true"
        t ok_skipped            SKIPPED <<<"ep_test -d    1 true"
        t ok_waived_skipped     SKIPPED <<<"ep_test -w -d 1 true"
        t failed                FAILED  <<<"ep_test       1 false"
        t failed_waived         WAIVED  <<<"ep_test -w    1 false"
        t failed_waived_skipped SKIPPED <<<"ep_test -w -d 1 false"
        t failed_skipped        SKIPPED <<<"ep_test -d    1 false"
    ); ep_suite_end

    ep_suite_begin two; (
        ep_suite_init
        t fail_fail       FAILED    <<<"
            ep_test       1 false;    ep_test       2 false"
        t fail_waive      FAILED    <<<"
            ep_test       1 false;    ep_test -w    2 true"
        t fail_ok         FAILED    <<<"
            ep_test       1 false;    ep_test       2 true"

        t waive_fail      FAILED    <<<"
            ep_test -w    1 true;     ep_test       2 false"
        t waive_waive     WAIVED    <<<"
            ep_test -w    1 true;     ep_test -w    2 true"
        t waive_ok        WAIVED    <<<"
            ep_test -w    1 true;     ep_test -w    2 true"

        t ok_fail         FAILED    <<<"
            ep_test       1 true;     ep_test       2 false"
        t ok_waive        WAIVED    <<<"
            ep_test       1 true;     ep_test -w    2 true"
        t ok_ok           PASSED    <<<"
            ep_test       1 true;     ep_test       2 true"
    ); ep_suite_end
); ep_suite_end

ep_suite_begin suite; (
    ep_suite_init

    ep_suite_begin one; (
        ep_suite_init
        ep_suite_begin executable; (
            ep_suite_init
            t empty         PASSED    <<<"ep_suite       1"
            t empty_waived  WAIVED    <<<"ep_suite -w    1"
        ); ep_suite_end

        ep_suite_begin inline; (
            ep_suite_init

            declare mask
            declare opts
            declare script
            declare status
            declare script_var
            declare -r script_empty=""
            declare -r script_skipped="ep_test -d 1"
            declare -r script_passed="ep_test 1 true"
            declare -r script_waived="ep_test -w 1"
            declare -r script_failed="ep_test 1 false"
            declare -r script_errored="false"
            declare -r script_panicked="ep_teardown_push false"
            declare -r script_aborted="ep_abort"

            while read mask opts script status; do
                script_var="script_$script"
                t ${mask}_${script} $status <<<"
                    ep_suite_begin $opts 1; (
                        ep_suite_init
                        ${!script_var}
                    ); ep_suite_end"
            done <<<"\
                asis        --  empty       PASSED
                asis        --  skipped     SKIPPED
                asis        --  passed      PASSED
                asis        --  waived      WAIVED
                asis        --  failed      FAILED
                asis        --  errored     ERRORED
                asis        --  panicked    PANICKED
                asis        --  aborted     ABORTED
                waived      -w  empty       WAIVED
                waived      -w  skipped     SKIPPED
                waived      -w  passed      WAIVED
                waived      -w  waived      WAIVED
                waived      -w  failed      WAIVED
                waived      -w  errored     ERRORED
                waived      -w  panicked    PANICKED
                waived      -w  aborted     ABORTED
                disabled    -d  empty       SKIPPED
                disabled    -d  skipped     SKIPPED
                disabled    -d  passed      SKIPPED
                disabled    -d  waived      SKIPPED
                disabled    -d  failed      SKIPPED
                disabled    -d  errored     SKIPPED
                disabled    -d  panicked    SKIPPED
                disabled    -d  aborted     SKIPPED"
        ); ep_suite_end
    ); ep_suite_end

); ep_suite_end
